# .github/workflows/ci.yml
name: AI UI Critic CI

on:
  push:
    branches: [ main ] # Trigger on push to main branch
  pull_request:
    branches: [ main ] # Trigger on pull requests targeting main

jobs:
  lint-and-format:
    name: Lint & Format Check (Client)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client # Run commands in client directory
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Use Node version matching your dev env
          cache: 'npm'
          cache-dependency-path: client/package-lock.json

      - name: Install dependencies
        run: npm ci # Use ci for clean installs

      - name: Run ESLint
        run: npm run lint

      # Optional: Add Prettier check if not fully covered by lint
      # - name: Check Formatting
      #   run: npm run format -- --check # Add a check script if needed

  test-client:
    name: Test Frontend (Client)
    runs-on: ubuntu-latest
    needs: lint-and-format # Run after linting passes
    defaults:
      run:
        working-directory: ./client
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: client/package-lock.json

      - name: Install dependencies
        run: npm ci

  test-server:
    name: Test Backend (Server)
    runs-on: ubuntu-latest
    # No 'needs' needed if it can run in parallel with client tests
    defaults:
      run:
        working-directory: ./server
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: server/package-lock.json

      - name: Install dependencies
        run: npm ci

  # build-client: # Optional: Add a build step check
  #   name: Build Frontend (Client)
  #   runs-on: ubuntu-latest
  #   needs: test-client
  #   defaults:
  #      run:
  #         working-directory: ./client
  #   steps:
  #      - name: Checkout code
  #        uses: actions/checkout@v3
  #      - name: Set up Node.js
  #        uses: actions/setup-node@v3
  #        # ... setup node ...
  #      - name: Install dependencies
  #        run: npm ci
  #      - name: Build project
  #        env:
  #           CI: false # Sometimes needed for CRA builds in CI
  #           REACT_APP_API_URL: /api # Example for production build proxying
  #        run: npm run build

  # Add Deployment jobs here later (e.g., deploy to Vercel/Render on merge to main)